### ISSUE TITLE
Collision Avoidance Error

### ISSUE THREAD

**Issue by yijiangh** [JeroenDM/descartes_tutorials#6] opened 2017-06-06 15:23 UTC
With planner's collision avoidance turned on in [this line](https://github.com/JeroenDM/descartes_tutorials/blob/6b07a57a9b4db0cc7966dafab2a299507f4c2671/descartes_tutorials/src/tutorial2.cpp#L155), I'm wondering why the generated motion is obviously in collision with the table and working part?

![2017-06-06_111917.png](https://s4.postimg.org/qc2y8jmd9/2017-06-06_111917.png)

**Comment by JeroenDM** [comment] 2017-06-09 07:17
Do you use the modified version of the descartes package found [here](https://github.com/JeroenDM/descartes/tree/welding_tutorial)? I should maybe mention this more explicit in the README and give this branch a better name, like "collision_checking_patch" instead of "welding_tutorial".

If you are using this modified version, the problem lies probably in that patch and I should look into that.

**Comment by JeroenDM** [comment] 2017-06-09 07:18
Also, thanks for testing the tutorial! :)

**Comment by yijiangh** [comment] 2017-08-16 15:59
@JeroenDM Thx for your reply. I just tested your patch on descartes and the general robot's pose is correct now, successfully avoiding collision with table. But if we take a closer look at the end effector (please check the video [here](https://youtu.be/o6gVSahh18o) (around 00:04)), you'll see the end effector actually did collide with the work piece. Any thought on this?

**Comment by JeroenDM** [comment] 2017-08-16 16:23
@yijiangh The problem in your video is similar to what we also encountered during our simulations. I'm pretty sure this happens because there is no collision checking done in between the trajectory points. When executed by the controller no additional collision checking is done.

An obvious solution is increasing the number of trajectory points, which is easy to change on [this line](https://github.com/JeroenDM/descartes_tutorials/blob/4e6f01036f9767dcc14b780967e4244a1732be75/descartes_tutorials/src/tutorial2.cpp#L115) of the tutorial. (I thought we had discussed this in the new tutorial, but now I see we forgot this...)

It is related to the problem discussed on [this mailing list topic](https://groups.google.com/forum/#!topic/swri-ros-pkg-dev/LOzZXvTTgVQ). During the strange "joint flip" a collision could also occur without it being detected by the Descartes planner.

**Comment by JeroenDM** [comment] 2017-08-16 16:29
In September we will present our evaluation of Descartes at [ETFA 2017](https://www.etfa2017.org/technical_program). When the article becomes public I will post a link (if I have figured out copyright issues... I'm new to this). The issue is discussed in the article, so it may be helpful here.

In the mean time, don't hesitate to ask me questions :)

**Comment by yijiangh** [comment] 2017-08-16 17:37
Cool! Looking forward to reading your paper!

I'm wondering: if this patch is so important to collision avoidance, is there a reason that it hasn't it been merged into the main branch?

**Comment by JeroenDM** [comment] 2017-08-16 20:53
Interesting, I have never actually asked anyone why. There is also a lot of new stuff in the different branches of the original [descartes repo](https://github.com/ros-industrial-consortium/descartes) that I have not looked at in detail.

In general, there are a lot of suggestions discussed in the GitHub issues that could significantly improve Descartes. It would be interesting to organize a major overhaul in cooperation with ROS Industrial.

I'm still in the process of researching the specific goal or direction of my PhD, maybe I can squeeze that in somewhere :)

But I'm going off-topic here... Maybe it is interesting to create the relevant issues in the original Descartes repo if they do not exist yet.

Do you agree that I close this issue?

**Closed as completed** 2017-08-16 20:55 UTC
